### ISSUE TITLE
Checklist towards alpha release

### ISSUE THREAD

**Issue by zspitz** [zspitz/DateTimeVisualizer#3]
- [x] Solve https://github.com/zspitz/Periscope/issues/23
- [x] Set up CI
- [x] README with screenshots
  - Describe the ambiguity of DateTimeKind.Unspecified
  - Describe how a local date/time can refer to 1, 2 or 0 `Instant`s
  - Requirements: .NET Framework 4.5+, .NET Standard 2.0
  - Installation
  - Uninstallation
  - Build
  - Contributing / Feedback
  - Credits
  - Resources
- [ ] Question: is list of providers the same on debugger and debuggee side, if using the same version of NodaTime?
- [x] Post on NodaTime mailing list
